## Getting data

```{r}
if (!file.exists('data')) dir.create('data')

training.data.path <- 'data/pml-training.csv'
if (!file.exists(training.data.path)) {
  training.data.url <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv'
  download.file(training.data.url, destfile=training.data.path, method='curl' )

}

training.data <- read.csv(training.data.path)

testing.data.path <- 'data/pml-testing.csv'
if (!file.exists(testing.data.path)) {
  testing.data.url <- 'https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv'
  download.file(testing.data.url, destfile=testing.data.path, method='curl' )
}
testing.data <- read.csv(testing.data.path)
```

## Pre-processing

```{r}
N <- ncol(training.data)

hasNoNAs <- apply(training.data, 2,
                  function(col) { all(!is.na(col)) })
training.data.1 <- training.data[,hasNoNAs]
hasNoDIVs <- apply(training.data.1, 2,
                  function(col) { all(col!="#DIV/0!") })

training.data.2 <- training.data.1[,hasNoDIVs]

training.data.3 <- training.data.2[,8:length(colnames(training.data.2))] 

```


## Data slitting

```{r}
require(caret)
set.seed(12345)
trainIndex <- createDataPartition(training.data.3$classe, p = .7,
                                  list = FALSE)

length(trainIndex)

dataTrain <- training.data.3[ trainIndex,]
dataTest  <- training.data.3[-trainIndex,]
```


## Models

### Linear Discriminant Analysis

```{r}
require(MASS)
classeInx <- ncol(dataTrain)
lda.fit <- lda(classe~., data=dataTrain)
ldaPredTrain <- predict(lda.fit, dataTrain)
confusionMatrix(ldaPredTrain$class, dataTrain$classe)
```



### Trees

```{r}
tree.fit <- train(classe ~ ., data = dataTrain, method="rpart")
treePredTrain <- predict(tree.fit, dataTrain)
confusionMatrix(treePredTrain, dataTrain$classe)
```

### Bagging and Random forest

```{r}
rf.bag <- train(classe ~ ., data = dataTrain, ntree=10)
rfPredTrain <- predict(rf.bag, dataTrain)
confusionMatrix(rfPredTrain, dataTrain$classe)
```

### Boosting

```{r}
## boosting <- train(classe ~ ., data = dataTrain, method="gbm", verbose =F)
## boostPredTrain <- predict(boosting, dataTrain)
## confusionMatrix(boostPredTrain, dataTrain$classe)
```

## Testing

```{r}
rfPredTest <- predict(rf.bag, dataTest)
confusionMatrix(rfPredTest, dataTest$classe)
```

## Our predictions for testing.data

```{r}
answers  <- predict(rf.bag2, testing.data)
answers 
```
